name: First Workflow

# Allows you to run this workflow manually from the Actions tab
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello, World!!"
      - name: Print Goodbye
        run: echo "Done Goodbye!"
        
